<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 */
if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = __('New Products');
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
}
?>

<?php if ($exist):?>
    <div class="block widget block-new-products <?= /* @escapeNotVerified */ $mode ?>">
        <div class="block-content">
            <?= /* @escapeNotVerified */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @escapeNotVerified */ $mode ?> <?= /* @escapeNotVerified */ $mode ?>">
                <ol class="product-items <?= /* @escapeNotVerified */ $type ?>">
                    <?php foreach ($items as $_item): ?>






                        <li class="item product product-item">
                            <div class="product-item-info" data-container="product-grid">
                                <?php // Product Image ?>
                                <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="product-item-photo">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                    <?php $_coloursAttr = $_item->getResource()->getAttribute('colours');
                                    $attrTestValue = explode(', ', $_coloursAttr->getFrontend()->getValue($_item));
                                    if(count($attrTestValue)) {
                                        echo '<span class="colours">';
                                        foreach ($attrTestValue as $a) {
                                            switch ($a) {
                                                case "Белый":
                                                    echo '<span class="white"></span>';
                                                    break;
                                                case "Сиреневый":
                                                    echo '<span class="purple"></span>';
                                                    break;
                                                case "Синий":
                                                    echo '<span class="blue"></span>';
                                                    break;
                                                case "Красный":
                                                    echo '<span class="red"></span>';
                                                    break;
                                                case "Желтый":
                                                    echo '<span class="yellow"></span>';
                                                    break;
                                                case "Зеленый":
                                                    echo '<span class="green"></span>';
                                                    break;
                                                case "Черный":
                                                    echo '<span class="black"></span>';
                                                    break;
                                                case "Коричневый":
                                                    echo '<span class="brown"></span>';
                                                    break;
                                            }
                                        }
                                        echo '</span>';
                                    }
                                    ?>
                                </a>
                                <div class="product details product-item-details">
                                    <div class="product-item-inner">




                                            <div class="product actions product-item-actions">
                                                <div class="actions-primary">
                                                    <?php if ($_item->isSaleable()): ?>
                                                        <?php if (!$_item->getTypeInstance()->isPossibleBuyFromList($_item)): ?>
                                                            <button class="action tocart primary"
                                                                    data-mage-init='{"redirectUrl":{"url":"<?= /* @escapeNotVerified */ $block->getAddToCartUrl($_item) ?>"}}'
                                                                    type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                                <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                            </button>
                                                        <?php else: ?>
                                                            <?php
                                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                            ?>
                                                            <button class="action tocart primary"
                                                                    data-post='<?= /* @escapeNotVerified */ $postData ?>'
                                                                    type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                                <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                            </button>
                                                        <?php endif; ?>
                                                    <?php else: ?>
                                                        <?php if ($_item->getIsSalable()): ?>
                                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                                        <?php else: ?>
                                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                                <div class="actions-secondary" data-role="add-to-links">
                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                        <a href="#"
                                                           data-post='<?= /* @escapeNotVerified */ $block->getAddToWishlistParams($_item) ?>'
                                                           class="action towishlist" data-action="add-to-wishlist"
                                                           title="<?= /* @escapeNotVerified */ __('Add to Wish List') ?>">
                                                            <span><?= /* @escapeNotVerified */ __('Add to Wish List') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            </div>









                                    </div>

                                    <div class="product-item--name-price">
                                        <strong class="product name product-item-name">
                                            <a class="product-item-link"
                                               href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>">
                                                <?= $block->escapeHtml($_item->getName()) ?>
                                                <em><?= /* @escapeNotVerified */ $_item->getSku() ?></em>
                                            </a>
                                        </strong>
                                        <?php echo $block->getProductPriceHtml($_item, $type); ?>
                                    </div>
                                </div>
                            </div>
                        </li>
                    <?php endforeach ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>
