<script type="text/x-magento-init">
{
    "*": {
        "home": {}
    }
}
</script>

<div class="home--hero hero--3">
    <div class="home--hero-row">
        <div class="home--hero-left">
            <h1>Шторы на&nbsp;заказ, ткани и аксессуары для&nbsp;штор</h1>
            <p>Индивидуальный пошив штор на&nbsp;заказ, большой опыт в&nbsp;оформлении квартир, коттеджей, офисов и&nbsp;гостиниц</p>
        </div>
        <div class="home--hero-right">
<!--            <img class="img--1" src="--><?php //echo $this->getViewFileUrl('images/home/hero-1.jpg'); ?><!--" />-->
<!--            <img class="img--2" src="--><?php //echo $this->getViewFileUrl('images/home/hero-2.jpg'); ?><!--" />-->
            <img class="img--3" src="<?php echo $this->getViewFileUrl('images/home/hero-3.jpg'); ?>" />
            <p>Индивидуальный пошив штор на заказ, большой опыт в оформлении квартир, коттеджей, офисов и гостиниц</p>
        </div>
    </div>
</div>
<div class="home--categories">
    <h2>Каталог ткани</h2>
    <div class="swiper-container swiper--home-categories">
        <div class="swiper-wrapper">
            <div class="swiper-slide">
                <a href="/catalogue/curtains">
                    <img src="<?php echo $this->getViewFileUrl('images/home/1.jpg'); ?>" srcset="<?php echo $this->getViewFileUrl('images/home/12x.jpg'); ?>" />
                    Для штор
                </a>
            </div>
            <div class="swiper-slide">
                <a href="/catalogue/furniture">
                    <img src="<?php echo $this->getViewFileUrl('images/home/2.jpg'); ?>" srcset="<?php echo $this->getViewFileUrl('images/home/22x.jpg'); ?>" />
                    Для мебели
                </a>
            </div>
            <div class="swiper-slide">
                <a href="/catalogue/garden">
                    <img src="<?php echo $this->getViewFileUrl('images/home/3.jpg'); ?>" srcset="<?php echo $this->getViewFileUrl('images/home/32x.jpg'); ?>" />
                    Для беседки
                </a>
            </div>
            <div class="swiper-slide">
                <a href="/catalogue/tablecloth">
                    <img src="<?php echo $this->getViewFileUrl('images/home/4.jpg'); ?>" srcset="<?php echo $this->getViewFileUrl('images/home/42x.jpg'); ?>" />
                    Скатерти и салфетки
                </a>
            </div>
            <div class="swiper-slide">
                <a href="/catalogue/pillows">
                    <img src="<?php echo $this->getViewFileUrl('images/home/5.jpg'); ?>" srcset="<?php echo $this->getViewFileUrl('images/home/52x.jpg'); ?>" />
                    Покрывала и подушки
                </a>
            </div>
            <div class="swiper-slide">
                <a href="/catalogue/accessories">
                    <img src="<?php echo $this->getViewFileUrl('images/home/6.jpg'); ?>" srcset="<?php echo $this->getViewFileUrl('images/home/62x.jpg'); ?>" />
                    Аксессуары
                </a>
            </div>
        </div>
        <div class="swiper-pagination"></div>
    </div>
</div>