<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation" data-action="navigation">
    <!--ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?= /* @escapeNotVerified */ $_menu ?>
        <?= /* @escapeNotVerified */ $block->getChildHtml() ?>
    </ul-->
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <li role="presentation" class="li--home"><a class="main--menu-home" href="/"><?= /* @escapeNotVerified */ __('Home Page') ?></a></li>
        <li role="presentation" class="li--about-us"><span class="main--menu-dropdown"><?= /* @escapeNotVerified */ __('About Us') ?></span><span class="main--menu-dropdown-mobile"></span>
            <div class="main--menu-submenu">
                <ul>
                    <li>
                        <a href="/about-us/salon"><?= /* @escapeNotVerified */ __('Curtains Atelier') ?></a>
                    </li>
                    <li>
                        <a href="/about-us/our-designers"><?= /* @escapeNotVerified */ __('Our Team') ?></a>
                    </li>
                </ul>
            </div>
        </li>
        <li role="presentation" class="li--works"><a class="main--menu-dropdown" href="/gallery-of-works"><?= /* @escapeNotVerified */ __('Our Works') ?></a><span class="main--menu-dropdown-mobile"></span>
            <div class="main--menu-submenu blocks--2">
                <ul class="block--1">
                    <li>
                        <a href="/gallery-of-works/all-products-2019"><?= /* @escapeNotVerified */ __('This Year') ?></a>
                    </li>
                    <li>
                        <a href="/gallery-of-works/all-products-2018"><?= /* @escapeNotVerified */ __('Previous Year') ?></a>
                    </li>
                    <li>
                        <a href="/gallery-of-works/foto-provence"><?= /* @escapeNotVerified */ __('Provence Photo') ?></a>
                    </li>
                    <li>
                        <a href="/gallery-of-works/archive"><?= /* @escapeNotVerified */ __('All Works') ?></a>
                    </li>
                </ul>
                <ul class="block--2">
                    <li>
                        <strong>Шторы по&nbsp;стилю</strong>: <a href="/gallery-of-works/archive/provence">В&nbsp;стиле Прованс</a>, <a href="/gallery-of-works/archive/classical">В&nbsp;классическом стиле</a>, <a href="/gallery-of-works/archive/modern">В&nbsp;современном стиле</a>.
                    </li>
                    <li>
                        <strong>Шторы по&nbsp;помещениям</strong>: <a href="/gallery-of-works/archive/curtains-for-kitchen">Шторы для&nbsp;кухни</a>, <a href="/gallery-of-works/archive/curtains-for-living-room">Для&nbsp;гостиной/зала</a>, <a href="/gallery-of-works/archive/curtains-for-bedroom">Для&nbsp;спальни</a>, <a href="/gallery-of-works/archive/curtains-for-kids">Для&nbsp;детской</a>, <a href="/gallery-of-works/archive/curtains-for-bathroom">Для&nbsp;ванной</a>, <a href="/gallery-of-works/archive/curtains-for-cabinet">Для&nbsp;кабинета</a>, <a href="/gallery-of-works/archive/home">Для&nbsp;частного&nbsp;дома</a>, <a href="/gallery-of-works/archive/hall">Для&nbsp;прихожей</a>, <a href="/gallery-of-works/archive/stairs">На&nbsp;лестницу</a>, <a href="/gallery-of-works/archive/terrace">Для &nbsp;беседки,&nbsp;террасы</a>.
                    </li>
                    <li>
                        <strong>По&nbsp;фасону</strong>: <a href="/gallery-of-works/archive/lambrequins">Ламбрекены</a>, <a href="/gallery-of-works/archive/cafe-curtains">Шторы&nbsp;кафе</a>, <a href="/gallery-of-works/archive/short-curtains">Короткие&nbsp;шторы</a>, <a href="/gallery-of-works/archive/loops">Шторы на&nbsp;петлях</a>, <a href="/gallery-of-works/archive/eyelets">Шторы на&nbsp;люверсах</a>.
                    </li>
                    <li>
                        <strong>Подъемные шторы</strong>: <a href="/gallery-of-works/archive/roman-shades">Римские</a>, <a href="/gallery-of-works/archive/austrian-shades">Австрийские</a>, <a href="/gallery-of-works/archive/london">Лондонские</a>, <a href="/gallery-of-works/archive/french-curtains">Французские</a>.
                    </li>
                    <li>
                        <strong>Шторы по&nbsp;форме&nbsp;окна</strong>: <a href="/gallery-of-works/archive/corner">Угловые</a>, <a href="/gallery-of-works/archive/bay-window">Эркерные</a>, <a href="/gallery-of-works/archive/arch">Арочные</a>.
                    </li>
                    <li>
                        <strong>Другие изделия</strong>: <a href="/gallery-of-works/archive/bedspread">Покрывала&nbsp;и&nbsp;подушки</a>, <a href="/gallery-of-works/archive/seats">Сидушки&nbsp;и&nbsp;чехлы</a>, <a href="/gallery-of-works/archive/tablecloth">Скатерти</a>, <a href="/gallery-of-works/archive/decor-elements">Подхваты&nbsp;и&nbsp;декор</a>, <a href="/gallery-of-works/archive/ceiling">Потолок&nbsp;из&nbsp;ткани</a>.
                    </li>
                </ul>
            </div>
        </li>
        <li role="presentation" class="li--design"><a class="main--menu-dropdown" href="/design-of-curtains"><?= /* @escapeNotVerified */ __('Curtains Design') ?></a><span class="main--menu-dropdown-mobile"></span>
            <div class="main--menu-submenu">
                <ul>
                    <li>
                        <a href="/design-of-curtains/modern"><?= /* @escapeNotVerified */ __('Contemporary Style') ?></a>
                    </li>
                    <li>
                        <a href="/design-of-curtains/terrace"><?= /* @escapeNotVerified */ __('Curtains for Terrace') ?></a>
                    </li>
                    <li>
                        <a href="/design-of-curtains/heat-saving"><?= /* @escapeNotVerified */ __('Temperature Preserving Curtains') ?></a>
                    </li>
                    <li>
                        <a href="/design-of-curtains/kitchen"><?= /* @escapeNotVerified */ __('Order Curtains for Kitchen') ?></a>
                    </li>
                    <li>
                        <a href="/design-of-curtains/small-kitchen"><?= /* @escapeNotVerified */ __('Curtains for Small Kitchen') ?></a>
                    </li>
                    <li>
                        <a href="/design-of-curtains/kitchen-with-balcony"><?= /* @escapeNotVerified */ __('Curtains for Kitchen with a Balcony') ?></a>
                    </li>
                    <li>
                        <a href="/design-of-curtains/provence-style"><?= /* @escapeNotVerified */ __('Curtains in Provence Style') ?></a>
                    </li>
                </ul>
            </div>
        </li>
        <li role="presentation" class="li--catalogue"><a class="main--menu-dropdown" href="/catalogue"><?= /* @escapeNotVerified */ __('Fabrics Catalogue') ?></a><span class="main--menu-dropdown-mobile"></span>
            <div class="main--menu-submenu cols--2">
                <ul>
                    <li>
                        <a href="/catalogue/curtains"><?= /* @escapeNotVerified */ __('Fabrics for Curtains') ?></a>
                        <ul>
                            <li>
                                <a href="/catalogue/curtains/portiere"><?= /* @escapeNotVerified */ __('Fabrics for Portiere') ?></a>
                            </li>
                            <li>
                                <a href="/catalogue/curtains/tulle"><?= /* @escapeNotVerified */ __('Fabrics for Tulle') ?></a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="/catalogue/furniture"><?= /* @escapeNotVerified */ __('Fabrics for Furniture') ?></a>
                        <ul>
                            <li>
                                <a href="/catalogue/furniture/furniture-covers"><?= /* @escapeNotVerified */ __('Fabrics for Furniture covers') ?></a>
                            </li>
                            <li>
                                <a href="/catalogue/furniture/upholstery"><?= /* @escapeNotVerified */ __('Fabrics for Upholstery') ?></a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="/catalogue/garden"><?= /* @escapeNotVerified */ __('Fabrics for Garden') ?></a>
                    </li>
                    <li>
                        <a href="/catalogue/tablecloth"><?= /* @escapeNotVerified */ __('Fabrics for Tablecloth') ?></a>
                    </li>
                    <li>
                        <a href="/catalogue/pillows"><?= /* @escapeNotVerified */ __('Fabrics for Pillows') ?></a>
                    </li>
                    <li>
                        <a href="/catalogue/accessories"><?= /* @escapeNotVerified */ __('Accessories for Curtains') ?></a>
                    </li>
                    <li class="li--help">
                        <a href="/info/help" ><?= /* @escapeNotVerified */ __('Help info') ?></a>
                    </li>
                    <li>
                        <a href="/info/delivery"><?= /* @escapeNotVerified */ __('Shipping and Payment') ?></a>
                    </li>
                    <li>
                        <a href="/constructor">Конструктор</a>
                    </li>
                </ul>
            </div>
        </li>
        <li role="presentation" class="li--services"><span class="main--menu-dropdown"><?= /* @escapeNotVerified */ __('Services') ?></span><span class="main--menu-dropdown-mobile"></span>
            <div class="main--menu-submenu">
                <ul>
                    <li>
                        <a href="/about-us/price"><?= /* @escapeNotVerified */ __('Sewing Price') ?></a>
                    </li>
                    <li>
                        <a href="/design-of-curtains"><?= /* @escapeNotVerified */ __('Curtains Design') ?></a>
                    </li>
                    <li>
                        <a href="/about-us/cleaning"><?= /* @escapeNotVerified */ __('Curtains Care') ?></a>
                    </li>
                </ul>
            </div>
        </li>
        <li role="presentation" class="li--reviews"><a href="/about-us/feedback"><?= /* @escapeNotVerified */ __('Our Reviews') ?></a></li>
        <li role="presentation" class="li--mobile">
            <div class="mobile--header--phones">
                <a class="phone--066" href="tel:+380669579090">(066) 957-90-90<span class="whatsapp"></span><span class="viber"></span></a>
                <a class="phone--067" href="tel:+380679579090">(067) 957-90-90</a>
                <a class="phone--044" href="tel:+380442904790">(044) 290-47-90</a>
            </div>
            <div class="header--links">
                <a class="header--location" href="/info/delivery#find_us"><?= /* @escapeNotVerified */ __('Our Location') ?></a>
                <a class="header--contact" href="/contact/"><span><?= /* @escapeNotVerified */ __('Contact Us') ?></span></a>
            </div>
        </li>
    </ul>
</nav>
