<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<p class="toolbar-amount" id="toolbar-amount">
    <?php if ($block->getLastPageNum() > 1): ?>
        <?php /* @escapeNotVerified */ echo __('Items %1&ndash;%2 of %3',
            '<span class="toolbar-number">' . $block->getFirstNum() . '</span>',
            '<span class="toolbar-number">' . $block->getLastNum() . '</span>',
            '<span class="toolbar-number">' . $block->getTotalNum() . '</span>') ?>
    <?php elseif ($block->getTotalNum() == 1 || ($block->getTotalNum() % 10 === 1 && $block->getTotalNum() > 20)): ?>
        <?php /* @escapeNotVerified */ echo __('%1 1Item',
           '<span class="toolbar-number">' . $block->getTotalNum() . '</span>') ?>
    <?php elseif (($block->getTotalNum() % 10 === 2 || $block->getTotalNum() % 10 === 3 || $block->getTotalNum() % 10 === 4) && ($block->getTotalNum() > 20 || $block->getTotalNum() < 10)): ?>
        <?php /* @escapeNotVerified */ echo __('%1 2Items',
            '<span class="toolbar-number">' . $block->getTotalNum() . '</span>') ?>
    <?php else: ?>
        <?php /* @escapeNotVerified */ echo __('%1 5Items',
            '<span class="toolbar-number">' . $block->getTotalNum() . '</span>') ?>
    <?php endif; ?>
</p>
