<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div class="toolbar-sorter sorter">
    <span class="toolbar-sorter--hidden">
        <label class="sorter-label" for="sorter"><?= /* @escapeNotVerified */ __('Sort By') ?></label>
        <select id="sorter" data-role="sorter" class="sorter-options">
            <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
                <option value="<?= /* @escapeNotVerified */ $_key ?>"
                    <?php if ($block->isOrderCurrent($_key)): ?>
                        selected="selected"
                    <?php endif; ?>
                >
                    <?= $block->escapeHtml(__($_order)) ?>
                </option>
            <?php endforeach; ?>
        </select>
         <a title="<?= /* @escapeNotVerified */ __('Set Ascending Direction') ?>" href="#" class="action sorter-action sort-desc<?php if ($block->getCurrentDirection() == 'asc'): ?> active<?php endif; ?>" data-role="direction-switcher" data-value="asc">
            <span><?= /* @escapeNotVerified */ __('Set Ascending Direction') ?></span>
        </a>
        <a title="<?= /* @escapeNotVerified */ __('Set Descending Direction') ?>" href="#" class="action sorter-action sort-asc<?php if ($block->getCurrentDirection() == 'desc'): ?> active<?php endif; ?>" data-role="direction-switcher" data-value="desc">
            <span><?= /* @escapeNotVerified */ __('Set Descending Direction') ?></span>
        </a>
        <span class="items pages-items pages item">
            <a href="#" class="sorting--a page"></a>
        </span>
    </span>
    <?= /* @escapeNotVerified */ __('Price') ?>:

    <span title="<?= /* @escapeNotVerified */ __('Set Ascending Direction') ?>" class="sorter--action sort--desc<?php if ($block->getCurrentDirection() == 'asc' and $block->getCurrentOrder() == 'price'): ?> active<?php endif; ?>" data-sort="asc">
        <span><?= /* @escapeNotVerified */ __('Set Ascending Direction') ?></span>
    </span>
    <span title="<?= /* @escapeNotVerified */ __('Set Descending Direction') ?>" class="sorter--action sort--asc<?php if ($block->getCurrentDirection() == 'desc' and $block->getCurrentOrder() == 'price'): ?> active<?php endif; ?>" data-sort="desc">
        <span><?= /* @escapeNotVerified */ __('Set Descending Direction') ?></span>
    </span>
    <?php if ($block->getCurrentOrder() == 'price'): ?><span class="sorter--remove"></span><?php endif; ?>
</div>

