<?php $feAttributes = array('country', 'delivery_time', 'fabrics_type' , 'fabrics_width', 'embroidery_width', 'pattern', 'horizontal_rapport', 'vertical_rapport', 'pattern_orientation', 'pattern_orientation_in_roll', 'rotatable_pattern', 'style', 'gamma', 'shine', 'sides', 'washable', 'dry_clean', 'ironing',  'weightning'); ?>
<ul>
<?php foreach ($feAttributes as $a): ?>
    <?php $attribute = $block->getProduct()->getResource()->getAttribute($a); ?>
    <?php $aValue = $attribute->getFrontend()->getValue($block->getProduct()); ?>
    <?php if($aValue): ?>
        <li>
        <?php echo $aName = $attribute->getStoreLabel() . ': '; ?>
        <?php echo $aValue; ?>
        </li>
    <?php endif; ?>
<?php endforeach; ?>
</ul>

<?php $_coloursAttr = $block->getProduct()->getResource()->getAttribute('colours');
$attrTestValue = explode(', ', $_coloursAttr->getFrontend()->getValue($block->getProduct()));
if(count($attrTestValue)) {
    echo '<ul class="pdp--colours">';
    foreach ($attrTestValue as $a) {
        switch ($a) {
            case "Белый":
                echo '<li class="white">Оттенки белого цвета</li>';
                break;
            case "Сиреневый":
                echo '<li class="purple">Оттенки сиреневого и розового цвета</li>';
                break;
            case "Синий":
                echo '<li class="blue">Оттенки синего и голубого цвета</li>';
                break;
            case "Красный":
                echo '<li class="red">Оттенки красного и оранжевого цвета</li>';
                break;
            case "Желтый":
                echo '<li class="yellow">Оттенки желтого цвета</li>';
                break;
            case "Зеленый":
                echo '<li class="green">Оттенки зеленого цвета</li>';
                break;
            case "Черный":
                echo '<li class="black">Оттенки серого и черного цвета</li>';
                break;
            case "Коричневый":
                echo '<li class="brown">Оттенки коричневого цвета</li>';
                break;
        }
    }
    echo '</ul>';
}
?>


