<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if (($_products = $block->getProductCollection()) && $_products->getSize()): ?>
    <div class="block-new-products-list">
        <h2><?= /* @escapeNotVerified */ __('New Products') ?></h2>
        <?php $suffix = $block->getNameInLayout(); ?>
        <div class="swiper-container widget-new-products">
            <div class="swiper-wrapper">
                <?php foreach ($_products->getItems() as $_product): ?>
                    <div class="swiper-slide">
                        <div class="product-item-info">
                            <a class="product-item-photo" href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>"
                               title="<?= /* @escapeNotVerified */ $block->stripTags($_product->getName(), null, true) ?>">
                                <?= $block->getImage($_product, 'side_column_widget_product_thumbnail')->toHtml() ?>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>"
                                       title="<?= /* @escapeNotVerified */ $block->stripTags($_product->getName(), null, true) ?>)" class="product-item-link">
                                        <?= /* @escapeNotVerified */ $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getName(), 'name') ?>
                                        <em><?= /* @escapeNotVerified */ $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getSku(), 'sku') ?></em>
                                    </a>
                                </strong>
                                <?= /* @escapeNotVerified */ $block->getProductPriceHtml($_product, '-widget-new-' . $suffix) ?>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
            <div class="widget-new-products-pagination"></div>
            <div class="widget-new-products-button-prev"></div>
            <div class="widget-new-products-button-next"></div>
        </div>
    </div>
    <script>
        require(['swiper'], function(Swiper) {
            var newProductsSwiper = new Swiper('.widget-new-products', {
                spaceBetween: 15,
                speed: 600,
                slidesPerView: 'auto',
                loop: true,
                pagination: {
                    el: '.widget-new-products-pagination',
                    clickable: true
                },
                navigation: {
                    nextEl: '.widget-new-products-button-next',
                    prevEl: '.widget-new-products-button-prev'
                },
                breakpoints: {
                    767: {
                        slidesPerView: 1
                    }
                }
            });
        });
    </script>
<?php endif; ?>
